# Generated by Django 3.2.7 on 2021-09-25 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(max_length=200)),
                ('complain', models.CharField(max_length=200)),
                ('appointment_status', models.CharField(default='Ongoing', max_length=200)),
                ('payment_status', models.CharField(default='Pending', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='available_schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctor_lastname', models.CharField(max_length=200)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='available_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=200)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='bills_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=200)),
                ('bill_month', models.CharField(default='January', max_length=200)),
                ('bill_year', models.CharField(default='2020', max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_by', models.CharField(max_length=200)),
                ('date_paid', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_type', models.CharField(max_length=200)),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='item_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=200)),
                ('itemcategory', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('item_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('units', models.CharField(max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('expiry_status', models.CharField(default='Not yet Expired', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('profile_type', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
                ('profile_fulladress', models.CharField(max_length=200)),
                ('bday', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('ecp_fullname', models.CharField(max_length=200)),
                ('ecp_contactnum', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
                ('ecp_relationship', models.CharField(max_length=200)),
                ('ecp_fulladress', models.CharField(max_length=200)),
                ('added', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tools_items_used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('units', models.CharField(max_length=200)),
                ('item_tools_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_used', models.DateField()),
                ('appointment_id', models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.appointment_details')),
                ('item_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.item_inventory')),
            ],
        ),
        migrations.CreateModel(
            name='stock_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.IntegerField(default=0)),
                ('units', models.CharField(max_length=200)),
                ('date_added', models.DateField()),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('item_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.item_inventory')),
            ],
        ),
        migrations.CreateModel(
            name='salary_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tips', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('severance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('philhealth', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagibig', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_given', models.DateField()),
                ('profile_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.profile')),
            ],
        ),
        migrations.CreateModel(
            name='salary_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exp_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.expense')),
                ('salary_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.salary_info')),
            ],
        ),
        migrations.CreateModel(
            name='procedures_done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedures_done', models.CharField(max_length=200)),
                ('teeth_position', models.CharField(default='None', max_length=200)),
                ('procedures_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment_id', models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.appointment_details')),
            ],
        ),
        migrations.CreateModel(
            name='prescription_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='None', max_length=200)),
                ('purchase_date', models.DateField()),
                ('item_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.item_inventory')),
                ('patient_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.profile')),
            ],
        ),
        migrations.CreateModel(
            name='prescription_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_by', models.CharField(max_length=200)),
                ('meds_prescription', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('units', models.CharField(max_length=200)),
                ('intake_instructions', models.CharField(default='None', max_length=1000)),
                ('date_given', models.DateField()),
                ('presc_status', models.CharField(default='Ongoing', max_length=200)),
                ('patient_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.profile')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=200)),
                ('date_paid', models.DateField()),
                ('appointment_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.appointment_details')),
            ],
        ),
        migrations.CreateModel(
            name='pat_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_occupation', models.CharField(max_length=200)),
                ('pat_allergies', models.TextField()),
                ('profile_id', models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.profile')),
            ],
        ),
        migrations.CreateModel(
            name='emp_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_position', models.CharField(max_length=200)),
                ('emp_status', models.CharField(max_length=200)),
                ('profile_id', models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.profile')),
            ],
        ),
        migrations.AddField(
            model_name='appointment_details',
            name='patient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.profile'),
        ),
        migrations.AddField(
            model_name='appointment_details',
            name='schedule_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.available_schedules'),
        ),
        migrations.AddField(
            model_name='appointment_details',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.available_services'),
        ),
    ]
