# Generated by Django 3.2.7 on 2021-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_auto_20210925_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_in',
            name='manufacturer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stock_in',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock_in',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
