# Generated by Django 3.2.7 on 2021-09-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0012_teeths_teeth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teeths_status',
            name='status',
            field=models.CharField(default='No data', max_length=200),
        ),
    ]
