# Generated by Django 3.2.7 on 2021-09-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0013_alter_teeths_status_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teeths',
            name='teeth_type',
        ),
    ]
