# Generated by Django 3.2.7 on 2021-09-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0015_alter_procedures_done_teeth_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedures_done',
            name='teeth_position',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
