# Generated by Django 3.2.7 on 2021-09-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0016_alter_procedures_done_teeth_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures_done',
            name='teeth_id',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='profiling.teeths'),
        ),
    ]
