# Generated by Django 3.2.7 on 2021-09-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0018_auto_20210928_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='teeths',
            name='teeth_type',
            field=models.CharField(default='Adult', max_length=200),
        ),
    ]
