# Generated by Django 3.2.7 on 2021-09-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0020_auto_20210929_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_purchase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
