# Generated by Django 3.2.7 on 2021-10-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0023_auto_20211004_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_inventory',
            name='barcode',
        ),
    ]
