# Generated by Django 3.2.7 on 2021-10-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0025_item_inventory_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_info',
            name='emp_position',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='emp_info',
            name='emp_status',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='pat_info',
            name='pat_allergies',
            field=models.TextField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='pat_info',
            name='pat_occupation',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
